name: Build Site

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Node.JS
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: yarn build
      run: |
        yarn install --dev
        yarn run build
      env:
        CI: true
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./out
